sudo: required

language: bash

services:
  - docker

script:
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then bash ./test/build_test.sh; fi'
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./test/build_test.sh && upload.sh; fi'
