apiVersion: v1
kind: Service
metadata:
  labels:
    test: mnjenkins
  name: mn-jenkins-deployment
  namespace: default
spec:
  ports:
  - nodePort: 31000
    port: 8080
  selector:
    test: mnjenkins
  type: NodePort
